### ISSUE TITLE
チャーター登録エラー

### ISSUE THREAD

**Issue by AriPSS** [miyabiit/kenki-catalogdb#1]
@centrevillage 
他社在庫商品一覧で「チャーターする」リンクをクリックするとエラーになります。
確認お願いします。
（これは、報告を貰っている属性情報が引き継がれない問題と関係していますか）

使用したユーザは
会社コード：0001111
ユーザーID：testusr01
パスワード同じ

**Comment by centrevillage** [comment]
@AriPSS バグだったので修正しました。ご確認お願いします。

**Comment by AriPSS** [comment]
@centrevillage 確認しました。Closeします。
