### ISSUE TITLE
productsにカラム追加し、新規データに更新

### ISSUE THREAD

**Issue by AriPSS** [miyabiit/kenki-catalogdb#10]
@centrevillage 
productsに
* メーカー名
* 型式
* 呼称
の3つのカラムを追加する予定です。
アップロードのCSVファイルにも追加します。

**Comment by AriPSS** [comment]
@centrevillage 
#7 の対応に絡んで、products.csvに以下の3つの項目を追加しました。
productsに
メーカー名(=manufacture_name)
型式(=model_name)
呼称(=product_short_name)
の3つのカラム追加をお願いします。

**Comment by centrevillage** [comment]
@AriPSS `model_name` なんですが、Railsの予約語なので `product_model_name` に改名してもよいですか？

**Comment by centrevillage** [comment]
@AriPSS stock_products.csv の `video_url` にURLでない文字列 (product_code + '-01')が入っているのが気になります。今は特にURLパターンチェックとかやっていないのですが、後々やりたくなった時に困らないかなと少し思いました。

**Comment by AriPSS** [comment]
@centrevillage 勉強不足ですみません。改名問題ないです

**Comment by centrevillage** [comment]
@AriPSS 項目追加対応しました。ご確認ください。

**Comment by miyabiit** [comment]
@centrevillage products.csv の依頼、複数箇所に書いてしまったので、混乱してしまったかもしれません。改めて、ファイルを添付します。
この中の products.csv を、新たに追加した上記３つの項目だけ、「更新」することは可能でしょうか？　この作業の終了をもって、このissueのクローズとしようと思います。

[_2020032301.zip](https://github.com/miyabiit/kenki-catalogdb/files/4392376/_2020032301.zip)

**Comment by centrevillage** [comment]
@miyabiit 可能ですが、こちら (https://github.com/miyabiit/kenki-catalogdb/issues/7#issuecomment-602366749) を対応してからの方がスムーズそうなので、そちらから進めたいと思います。

**Comment by miyabiit** [comment]
@centrevillage 了解です。

**Comment by centrevillage** [comment]
@AriPSS @miyabiit こちらのproduct.csvをテスト環境に反映しましたので、ご確認お願いします。

**Comment by miyabiit** [comment]
@centrevillage サラッと確認しました。反映していると思います。クローズとします。
