### ISSUE TITLE
新規チャーター品登録画面に商品共通情報を表示（備忘録）

### ISSUE THREAD

**Issue by AriPSS** [miyabiit/kenki-catalogdb#11]
@centrevillage 
他社在庫情報一覧で「チャーターする」リンクをクリックした後に表示される「新規チャーター品登録」画面に選択した他社在庫品の商品共通情報を表示する。（新規自社在庫情報を登録する画面と同じように）

**Comment by centrevillage** [comment]
@AriPSS 対応しました。ご確認お願いします。

**Comment by AriPSS** [comment]
@centrevillage 確認しました。Closeします
