### ISSUE TITLE
自社在庫登録画面の仕様の入力桁数の拡張

### ISSUE THREAD

**Issue by AriPSS** [miyabiit/kenki-catalogdb#12]
@centrevillage 自社在庫登録画面の「仕様」の入力欄ですが、2000文字までの制約がありますので、3000文字まで増やしてもらえますか？

**Comment by centrevillage** [comment]
@AriPSS 増やしましたのでご確認ください。

**Comment by AriPSS** [comment]
@centrevillage 確認しました。closeします
