### ISSUE TITLE
一時的に全てのドメインからのXMLHttpRequestを許可してください

### ISSUE THREAD

**Issue by miyabiit** [miyabiit/kenki-catalogdb#13]
@centrevillage 開発サーバから、stagingサーバに、vueアプリをビルドしてリリース確認をしています。
まだ、いろいろとリリースの問題が解決していないのですが、CORS問題を避けるため、API側で、アクセスを許可してもらえませんか？
（開発用サーバでは、vue devserver:proxy で、proxy設定で逃げていたのですが、この機能は、開発モードのみで、productionではないのです。トホホ。
本番のドメインが決まりましたら、そのドメインを指定する依頼をかけたいと思います。

**Comment by centrevillage** [comment]
@miyabiit CORSの設定をしてみましたので、アクセスできるかご確認ください。

**Comment by miyabiit** [comment]
@centrevillage ありがとうございます。まだ、活躍できる時間帯ではないので、本日夜に確認します。

**Comment by miyabiit** [comment]
@centrevillage 残念ながら、アクセス出来ないですね。どこにもログが残らないので、こちらの問題かもしれず、もう少し検討します。

**Comment by centrevillage** [comment]
@miyabiit ブラウザからもCORS対応のリクエストを投げる必要があるので、それではないでしょうか。
jQueryだと `withCredentials` のようなパラメータを渡しますが、そこらへんはライブラリによって違うでしょうね。

https://qiita.com/umechiki/items/82dd43cd1465de5f5afe

**Comment by miyabiit** [comment]
@centrevillage withCredentials パラメータ等の設定、cookieの自動設定など、いろいろやってみたのですが、全てうまくいきません。現在、firefoxのconsoleで出ているエラーは、
`混在アクティブコンテンツ  “http://13.59.42.214/api/categories/search” の読み込みをブロックしました` です。
https://developer.mozilla.org/ja/docs/Security/%E6%B7%B7%E5%9C%A8%E3%82%B3%E3%83%B3%E3%83%86%E3%83%B3%E3%83%84/How_to_fix_website_with_mixed_content

このサイトの話だと、httpsにしなければならない感じです。このエラーとは別にcors関連のエラーも出ているようです。

curl で、別オリジンを指定して実施したところ、成功しました。（そもそも、curlは、いつでも成功する、問題はブラウザレベル）。
とりいそぎ、報告です。（さらになにかヒントがあればと期待して）

**Comment by centrevillage** [comment]
@miyabiit ローカルマシンでWebアプリを立ち上げて、ブラウザからスタージングに向けて POST リクエストでカテゴリの登録を行ってみたところ成功しました。

混在コンテンツのエラーが出ているということは、作成中のページはHTTPSでしょうか？
それだと、ステージング環境もHTTPSにしないとダメなのかもしれないですね。

**Comment by miyabiit** [comment]
@centrevillage 作成中のページは、HTTPSです。とりあえず、別issueでお願いした通り、staging をssl化してもらった後に、再挑戦します。

**Comment by miyabiit** [comment]
@centrevillage httpsでテストした結果、混在コンテンツ問題は、解決しました。
しかし、cors問題は、相変わらず発生中。
万策尽きたので、APIライブラリを Axios から、fetch APIに変更しました。結果は、成功しました。
これから、書き換えを行います。
ありがとうございます。このissueは、クローズします。
