### ISSUE TITLE
production環境の構築

### ISSUE THREAD

**Issue by miyabiit** [miyabiit/kenki-catalogdb#14]
@centrevillage AWS (メントルアカウント）のアジアパシフィックリージョン（東京）にて、カタログ電子版のproduction 環境を作成してください。domain は、既に取ってあります（kenki-db.com )ので、IPアドレスとったら連絡ください。www.kenki-db.com を割り当てます。また、現在のstaging環境ですが、test.kenki-db.com を割り当てます。ともに、Let's Encryptにて、常時ssl化してください。よろしくお願いします。

**Comment by miyabiit** [comment]
@centrevillage それから、データベースの中身ですが、stagingのものをダンプ＆リストアして入れてください。

**Comment by miyabiit** [comment]
@centrevillage https://test.kenki-db.com/api/ は、稼働していることを確認しました。

**Comment by centrevillage** [comment]
@miyabiit 本番インスタンスのプランは如何しましょうか？

<img width="1261" alt="スクリーンショット 2020-03-30 21 45 36" src="https://user-images.githubusercontent.com/1106404/77913854-f60c0100-72cf-11ea-9f5c-99d40ea52ff5.png">

どれぐらいのパフォーマンスが必要か分からなければとりあえずt2.microでいいでしょうか。

**Comment by miyabiit** [comment]
@centrevillage  スケールアップできたと思うので、とりあえず　t2.microからスタートしましょう。

**Comment by miyabiit** [comment]
@centrevillage とりあえず、一通りリリースしてもらったと思います。クローズします。
