### ISSUE TITLE
チャータ元が不明

### ISSUE THREAD

**Issue by miyabiit** [miyabiit/kenki-catalogdb#15]
@centrevillage chartered_stock_products は、他の会社のstock_productsを（借りてきた）copyしてきたレコードだと理解しています。chartered_stock_productsに、チャータ元会社のid をセットしてほしい。
例えば、charter_company_id をコピー時にセットするとか。

**Comment by centrevillage** [comment]
@miyabiit 
`/api/chartered_stock_products` の `stock_products.company_id` 項目にてチャーター元会社のIDを返すように修正し、ステージング環境にあげました。
ご確認お願いします。

**Comment by miyabiit** [comment]
```
myUrl = 'https://test.kenki-db.com/api/chartered_stock_products/search'
param = {
  "limit": 100,
  "stock_product": {
      "company_id": 1
  }
}
```

上記の条件で、検索すると、以下のような結果が得られます。
確かに、結果では、以下の通り、OKなのですが、

``` 
stock_product : { company_id : 2, id: 276} 
```

検索条件指定と、結果表示の矛盾を感じます。
上記の検索の記述は、stock_product : { company_id : 1 } で、結果選ばれたレコードは、　会社1のchartered_stock_products です。
恐らく、 検索の時のstock_product と、結果のstock_product は、意味が異なると思うのですが、少々解説を戴けると嬉しいです。

```
[{'address_info': '埼玉営業所\r\n048-123-4567',
  'address_info_charterable': True,
  'address_info_published': True,
  'category': {'id': 415, 'name': '0.007m3（0.3ｔクラス）バックホー'},
  'category_id': 415,
  'charterable': False,
  'company': {'id': 1, 'name': 'テスト会社'},
  'company_id': 1,
  'company_memo': '',
  'created_at': '2020-03-19T16:47:21.320+09:00',
  'description': '備考1',
  'description_charterable': True,
  'description_published': True,
  'faq': '質問1\r\n回答1\r\n\r\n質問2\r\n回答2',
  'faq_charterable': True,
  'faq_published': True,
  'file_props': [],
  'id': 277,
  'image_props': [],
  'meta_description': '',
  'meta_keywords': '',
  'price_info': '10,000円',
  'price_info_charterable': True,
  'price_info_published': True,
  'private_memo': '',
  'product': {'checking_denhou': False,
              'checking_shaken': False,
              'checking_souken': False,
              'checking_teiji': False,
              'checking_tokujiken': True,
              'created_at': '2020-03-13T16:24:43.389+09:00',
              'description_a': None,
              'description_b': None,
              'driver_license': False,
              'id': 64,
              'manufacture_name': 'コマツ',
              'netis': False,
              'netis_limit_date': None,
              'product_code': 'kkl19120151',
              'product_model_name': 'PC01',
              'product_name': 'VCAA70AB',
              'product_short_name': '0.007m3（0.3ｔクラス）',
              'qualification_comment': None,
              'qualification_skill': False,
              'qualification_sp_teach': True,
              'title': '0.007m3（0.3ｔクラス）バックホー スタンダード PC01',
              'updated_at': '2020-04-07T23:42:32.120+09:00'},
  'product_id': 64,
  'spec': '',
  'spec_comment': 'チャーターしたもの',
  'staff_comment': '担当者\r\n担当者1',
  'staff_comment_charterable': True,
  'staff_comment_published': True,
  'stock_product': {'company_id': 2, 'id': 275},
  'stock_product_id': 275,
  'sub_categories': [],
  'text_props': [],
  'updated_at': '2020-03-19T16:47:21.320+09:00',
  'video_charterable': False,
  'video_comment': '',
  'video_license': '',
  'video_license_valid': False,
  'video_published': False,
  'video_url': ''},
（以下、レコード省略）
```

**Comment by centrevillage** [comment]
@miyabiit 
下記のようなクエリで、チャーター元の会社IDで絞り込みができる想定だったのですが、試してみたところうまく動きませんでした。

```
param = {
  "limit": 100,
  "stock_product": {
      "stock_product": {
        "company_id": 1
      }
  }
}
```

原因としては、自己参照テーブルの場合に検索ロジックが意図通りに機能しないバグがあるようです。
修正対応いたします。

**Comment by centrevillage** [comment]
@miyabiit 自己参照テーブルの検索に対応し、テスト環境にあげました。
上記コメントのクエリでチャーター元会社IDでの絞り込みができるはずです。

検索結果JSONについてですが、チャーター先会社IDは `company_id` 項目で、チャーター元会社IDは `stock_product.company_id` 項目に設定されます。
つまり、検索結果JSONの `stock_product` はチャーター元を表しますが、検索JSONはトップレベルの `stock_product` がチャーター先を表し、ネストした `stock_product` がチャーター元を表します。

こういう混乱が起きるのは、URL上のリソース名とJSON上のモデル名が異なることが原因と思います。
( `/api/chartered_stock_products` で検索JSONで指定するmodel名が `chartered_stock_product` でなく `stock_product` となっている等）

下記の様にURLのリソース名とJSON上のモデル名を一致させると混乱が少なくなるかと思いますが、いかがでしょうか:

POST /api/chartered_stock_products/search
```
{
  "chartered_stock_product": {
      "stock_product": {
        "company_id": 1
      }
  }
}
```

上記で問題なければ修正を行います。

**Comment by miyabiit** [comment]
@centrevillage 一連のコメントの中で、ステージング環境と、テスト環境の言葉出ていますが、同じサイトの事だとの理解であってますか？
自己参照テーブルの修正、ありがとうございます。これで、様子をみましょう。一度に複数の修正を行うと、何が問題だったのか、混乱してしまう気がします。検索仕様としては、URLのリソース名と、JSONのリソース名に気をつければ良いようですし、データベース（クラス）の構造をより理解すれば、何とかなりそうな気がします。
この件は、一旦、チャータ元を示す値のセットと自己参照テーブルの修正の終了にてクローズとします。

**Comment by centrevillage** [comment]
@miyabiit 
>  一連のコメントの中で、ステージング環境と、テスト環境の言葉出ていますが、同じサイトの事だとの理解であってますか？

同じです。ごっちゃになっててすみません・・・
