### ISSUE TITLE
アップロードした画像の保管方法など

### ISSUE THREAD

**Issue by miyabiit** [miyabiit/kenki-catalogdb#16]
@centrevillage 画像をアップロードした時の動作についての質問とお願い。

### お願い

* ファイル名の変更をしない
* アップロードしたファイルを保存する場所をソース外にしたい（将来の仕様として、その画像をユーザが直接updateする可能性がある。sftp 等によって）

### 質問

* api call した際に手に入るpath 情報に基づき、画像情報を取得（表示）できるか？

### 背景

現在は、ユーザが 画像名を product_code + 09.jpg のルールで設定しており、サイト側ではそのルールで画像を表示している。（サーバ側からの情報を取っていない。つまり、センターシステムに画像をアップしていなくても、画像を表示している）、将来は、全てセンター側からの取得としたいし、画像の一括アップも、実現したい。一括アップした場合、先ほどの命名ルールで、画像レコードの自動作成も検討したいが、それは、もう少し内容を検討した上での別issueとします。

**Comment by centrevillage** [comment]
@miyabiit 根本的なところなのですが、その画像とは在庫情報に紐づけられた画像属性とは別なのでしょうか？

CloudFront 対応のことを考えると、RailsのActiveStorage経由でS3に保存するのが良いように思います。
(現在のファイル属性、画像属性はそのようにする予定です）

やったことはないのですが、 AWS Transfer for SFTP  というサービスを使うとSFTP経由でS3にファイルアップロードは可能なようです。
https://docs.aws.amazon.com/ja_jp/transfer/latest/userguide/how-aws-transfer-works.html

**Comment by centrevillage** [comment]
@miyabiit ついでに確認したいのですが、CloudFront等のキャッシュサーバーを使う話が元々あったと思うのですが、適用範囲についてはいかがしましょうか？

現在キャッシュの対象にできそうなものといえば、下記ぐらいだと思っています：

- アップロードされたファイル属性
- アップロードされた画像属性
- 本issueで検討しているアップロード画像

**Comment by miyabiit** [comment]
@centrevillage 
* 「画像」は、在庫情報で紐づけられた画像属性も含みます。
* ActiveStorage経由のS3　攻撃で良いです。
* キャッシュサーバは是非やりましょう。対象は、上記3つでOKです。

よろしく、お願いします。

**Comment by miyabiit** [comment]
@centrevillage 
* 「画像」は、在庫情報で紐づけられた画像属性も含みます。
* ActiveStorage経由のS3　攻撃で良いです。
* キャッシュサーバは是非やりましょう。対象は、上記3つでOKです。

よろしく、お願いします。

**Comment by centrevillage** [comment]
@miyabiit 
> 現在は、ユーザが 画像名を product_code + 09.jpg のルールで設定しており、サイト側ではそのルールで画像を表示している

この様な処理をしている画像は、product(商品) に直接紐づく画像だけでしょうか？
他にもありますか？

他になければ、

- products に1対Nで関連する画像属性を追加

を行って、JSON経由で画像URLを取得できる様にすれば良いのかなと思っています。

**Comment by centrevillage** [comment]
S3とCloudFrontの件は別の話題なので、issueを分けてみました。

**Comment by miyabiit** [comment]
@centrevillage 「このような処理」は、product (stock_product)に紐づく画像だけです。json経由の1：n　属性の取得は面白そうですが、現在はこの件は「逃げの手」を打って誤魔化しているので、このissueは、S3とcloud Frontの実現のissueに別れることで、クローズとします。
（少々、依頼側の事情が変わってきたので、後でslackで、今後の話をします）

**Comment by centrevillage** [comment]
@miyabiit 誤解があるといけないので一点だけ。

画像属性については、結果JSON内の `image_props.url` プロパティに画像URLが設定されるので、基本的には利用サイト側はそれを `img` タグの `src` 属性に指定するなりして使う想定です。
（これについては、ファイルの保存先がサーバーのローカルファイルシステムでも、S3でもCloudFront経由でも同じです）

ただ、今の実装だと `image_props.url` に設定されているURLが、下記の様にホスト名がない形式となっています:

```
{
   ...,
    "image_props": [
      {
        "id": 1,
        "name": "テスト画像",
        "url": "/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ece345d851529c6e27b1ac1bf9c893cd38ee40c9/%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88%202020-04-14%2020.01.48.png"
      },
   ...
  }
```

ホスト名を補ってあげればいいのですが、利用サイト側でやってしまうとS3やCloudFront対応した時に直しが必要になってしまうので、APIサーバー側でホスト名を入れたURLを生成するように修正したいと思います。
