### ISSUE TITLE
ファイル・画像属性JSONのURLを完全形式にする

### ISSUE THREAD

**Issue by centrevillage** [miyabiit/kenki-catalogdb#19]
関連 #16

**Comment by centrevillage** [comment]
@miyabiit こちら、対応しました。
経緯についてはこちらをご確認ください。

https://github.com/miyabiit/kenki-catalogdb/issues/16#issuecomment-613378995

**Comment by miyabiit** [comment]
@centrevillage 了解しました。御気遣いありがとうございます。これにて、クローズとします。
