### ISSUE TITLE
照会権限ユーザーの他社在庫検索のチャーターリンクについて

### ISSUE THREAD

**Issue by AriPSS** [miyabiit/kenki-catalogdb#2]
照会権限のみのユーザーで他社在庫の「チャーターする」リンクを押せないようにして下さい。（現在、リンクをクリックするとログイン画面に遷移します）

**Comment by centrevillage** [comment]
@AriPSS 対応してテスト環境にあげましたのでご確認ください

**Comment by AriPSS** [comment]
@centrevillage 確認しました。Closeします
