### ISSUE TITLE
自社在庫CSVインポートエラー

### ISSUE THREAD

**Issue by AriPSS** [miyabiit/kenki-catalogdb#24]
会社ID=1の自社在庫商品のCSVインポートで、添付のファイルをインポートしようとしたところ添付のエラーが発生しました。

![自社在庫CSVインポートエラー_2020042101](https://user-images.githubusercontent.com/12669075/79837953-3b15e580-83ed-11ea-98da-6fe9d7e7ca11.JPG)

[stock_products_20200421.zip](https://github.com/miyabiit/kenki-catalogdb/files/4508342/stock_products_20200421.zip)

**Comment by centrevillage** [comment]
@AriPSS 
カテゴリ名の `〜` の部分が、登録されている分類名と異なる様です。

参考:「ウエーブダッシュ問題について」
ttp://blog.livedoor.jp/akiba_engineer/archives/330753.html

WIndows-31JからUTF-8に変換した場合とShift-JISからUTF-8に変換した場合でウェーブダッシュ記号の変換先の文字が異なることが原因のようです。

根本的な解決策としては、分類の登録時に文字の正規化を行うか、CSV自体を初めからUTF-8エンコーディングで作成（ExcelでCSV編集する場合は簡単ではないですが）するかだと思います。

**Comment by centrevillage** [comment]
@AriPSS 
文字の正規化の話については、以前の issue で話題にあげましたので、参考までに。

https://github.com/miyabiit/kenki-catalogdb/issues/7#issuecomment-597360514

**Comment by centrevillage** [comment]
@AriPSS 急ぎであれば、正規化まではやらずにとりあえず `〜` の文字だけ変換先が一意になる様にすることもできますが、いかがしましょうか

**Comment by AriPSS** [comment]
@centrevillage 一先ず、データを修正し、取り込みました
