### ISSUE TITLE
会社マスタ削除エラー

### ISSUE THREAD

**Issue by AriPSS** [miyabiit/kenki-catalogdb#25]
@centrevillage 会社マスタを削除しようとすると、エラーになります。確認をお願いします。
1つお願いがあります。本番サイト（kenki-db.com）に登録されている会社マスタの会社ID=1以外のマスタを削除して下さい（添付参照願います）

![会社マスタ_20200423](https://user-images.githubusercontent.com/12669075/80075114-253b2880-8585-11ea-806f-030c36f89cfb.JPG)

**Comment by centrevillage** [comment]
@AriPSS 会社削除に対応し、テスト環境 `test.kenk-db.com` にあげました。
ご確認お願いします。

**Comment by AriPSS** [comment]
@centrevillage 会社マスタの削除を確認しました。その後にユーザーメニューを選択したところエラー画面が表示されます。確認をお願いします。

**Comment by centrevillage** [comment]
@AriPSS 確認不足ですみませんでした。対応しました。

**Comment by AriPSS** [comment]
@centrevillage 確認しました。Closeします。本番リリースもお願いします
