### ISSUE TITLE
サブカテゴリの削除機能

### ISSUE THREAD

**Issue by AriPSS** [miyabiit/kenki-catalogdb#27]
@centrevillage 現在、サブカテゴリマスタのデータを削除出来ないので、削除出来るようにお願いします。

**Comment by centrevillage** [comment]
@AriPSS 対応し、テスト環境 `test.kenk-db.com` にあげました。
ご確認お願いします。

**Comment by AriPSS** [comment]
@centrevillage 確認しました。Closeします
