### ISSUE TITLE
自社在庫商品のダウンロードファイルと画像ファイルの削除について

### ISSUE THREAD

**Issue by AriPSS** [miyabiit/kenki-catalogdb#3]
自社在庫商品で複数のダウンロードファイル、画像ファイルを登録した時に削除が出来ない。（添付参照下さい）

![自社在庫_ダウンロードファイル](https://user-images.githubusercontent.com/12669075/74699514-36458180-5244-11ea-9f22-6a60cca0b402.JPG)

**Comment by centrevillage** [comment]
@AriPSS こちら、ブラウザは何を使用していますか？

**Comment by centrevillage** [comment]
自社在庫なのに公開フラグ入力が表示されていないのも変ですね・・・

**Comment by AriPSS** [comment]
@centrevillage なるほど、ブラウザはWin/Firefoxです。Win/Chromeでも確認してみます。

**Comment by AriPSS** [comment]
@centrevillage Win/Chromeではこのように表示されました。Win/Firefoxの場合とは少し違いますね。因みに、オペレーションは以下の通りです。
1.登録されている自社在庫を編集

2.ダウンロードファイルを「file03」、「file04」でアップロード

3.「file03」の方を削除すると、file03は削除されたように見えますが、2行表示される。
（因みに、右上の更新ボタンを押す前にダウンロードファイルを削除しています）

![Win_Chrome_バージョン_2020021901](https://user-images.githubusercontent.com/12669075/74813034-eea02200-5337-11ea-95a3-5c62094c52e8.JPG)

**Comment by AriPSS** [comment]
@centrevillage 新規で自社在庫登録の画面でも「提供」フラグが表示されないですね。Win/ChromeとWin/Firefoxで試しました。

![新規自社在庫登録_2020022001](https://user-images.githubusercontent.com/12669075/74908443-376bdf80-53f9-11ea-93b8-8bab5602c258.JPG)

**Comment by centrevillage** [comment]
@AriPSS こちら、再現できましたので対応しました（対応忘れていてすみません・・・）
ご確認お願いします。

**Comment by AriPSS** [comment]
@centrevillage 確認しました。Closeします
