### ISSUE TITLE
自社在庫一覧について

### ISSUE THREAD

**Issue by AriPSS** [miyabiit/kenki-catalogdb#4]
昨日（2/27）、会社ID=1で登録してもらった自社在庫情報を含めテストで登録した自社在庫が会社ID=2のユーザーでログインした場合でも同じように見えます。
※他社在庫情報であれば分かるのですが

![会社ID1の自社在庫情報_20200228](https://user-images.githubusercontent.com/12669075/75522486-74655100-5a4d-11ea-814d-24854e5c131a.JPG)

![会社ID2の自社在庫情報_20200228](https://user-images.githubusercontent.com/12669075/75522534-8e9f2f00-5a4d-11ea-8738-6fb0f2dc248a.JPG)

**Comment by centrevillage** [comment]
@AriPSS 確認が足りずすみません。
対応したのでご確認ください。

**Comment by AriPSS** [comment]
@centrevillage 確認しました。Closeします
