### ISSUE TITLE
分類マスタのアップロード登録順について

### ISSUE THREAD

**Issue by AriPSS** [miyabiit/kenki-catalogdb#40]
@centrevillage 
分類マスタの画面で見ると、分類マスタの登録順がアップロードしたファイルの登録順に見受けられないのですが、どうでしょうか？
参考までにアップロードしたファイルを添付します。
会社コード=CH-001の分です

[categories_2020090403.zip](https://github.com/miyabiit/kenki-catalogdb/files/5237899/categories_2020090403.zip)

**Comment by centrevillage** [comment]
@AriPSS 分類マスタの画面はソート順未指定なので、順番は保証されてないですね。
分類マスタIDの昇順（旧いものが上に来る）ソートするようにしましょうか？

**Comment by AriPSS** [comment]
@centrevillage 今のところ対応の必要ないです。一旦、Closeします
