### ISSUE TITLE
ステージング環境のチガサキレンタルのデータ削除依頼

### ISSUE THREAD

**Issue by AriPSS** [miyabiit/kenki-catalogdb#41]
@centrevillage 
先日、ステージング環境にアップロードしたチガサキレンタル（会社コード=CH-001）の
*分類マスタ（categories）
*商品共通（product）
*自社在庫（stock_product）
を削除して下さい。
出来れば、9/21（月）までに実行してもらえると助かります

**Comment by centrevillage** [comment]
@AriPSS 商品共通情報は会社との紐付けがないのですが、会社コード `CH-001` の `stock_products` のみに関連している products を削除という形になりますか？

**Comment by AriPSS** [comment]
@centrevillage 
そうですね。紐づけなかったでしたね。

>会社コード CH-001 の stock_products のみに関連している products を削除という形になりますか？
それでお願い出来ますか？

**Comment by centrevillage** [comment]
@AriPSS 削除完了しましたのでご確認ください。

**Comment by AriPSS** [comment]
@centrevillage ありがとうございました。

**Comment by AriPSS** [comment]
@centrevillage 
前回同様、削除お願いします

**Comment by centrevillage** [comment]
@AriPSS 作業完了しましたのでご確認ください

**Comment by AriPSS** [comment]
@centrevillage 確認しました。

**Comment by AriPSS** [comment]
@centrevillage 本日（10/2）22時以降に削除お願いします。明日でも大丈夫です

**Comment by centrevillage** [comment]
@AriPSS 作業完了しましたのでご確認ください

**Comment by AriPSS** [comment]
@centrevillage 有難うございます。確認しました
