### ISSUE TITLE
商品コード重複について確認

### ISSUE THREAD

**Issue by AriPSS** [miyabiit/kenki-catalogdb#42]
@centrevillage 
同じproduct_nameが別々のproduct_codeに設定することは可能でしょうか？

**Comment by centrevillage** [comment]
@AriPSS 

商品コード(product_name) は同じ名前を設定することができます。
一方、商品キー(product_code) は一意でないと登録できません。

**Comment by AriPSS** [comment]
@centrevillage 確認しました。
