### ISSUE TITLE
本番環境のチガサキレンタルのデータ削除依頼

### ISSUE THREAD

**Issue by AriPSS** [miyabiit/kenki-catalogdb#45]
@centrevillage 
先日、本番環境にチガサキレンタル（会社コード=CH-001）のデータをアップロードしました。
何回かステージング環境でお願いしている
*分類マスタ（categories）
*商品共通（product）
*自社在庫（stock_product）
を削除して下さい。（チガサキレンタル分のみ）

削除は今日（10/23）の22:00以降で明日中までにお願い出来ればと思います。

**Comment by centrevillage** [comment]
@AriPSS 作業完了しましたのでご確認ください。

**Comment by AriPSS** [comment]
@centrevillage 有難うございます。確認しました。
