### ISSUE TITLE
ステージング環境の電動舎のデータ削除依頼

### ISSUE THREAD

**Issue by AriPSS** [miyabiit/kenki-catalogdb#47]
@centrevillage 
ステージング環境にアップロードしてある電動舎（会社コード=DEN-001）の
*分類マスタ（categories）
*商品共通（product）
*自社在庫（stock_product）
を削除して下さい。

尚、作業をするかどうかは改めて連絡しますので、それまでは作業しなくてO.K.です！

**Comment by AriPSS** [comment]
@centrevillage 確認しました。

**Comment by AriPSS** [comment]
@centrevillage 再度、お願いします！

**Comment by AriPSS** [comment]
@centrevillage 確認しました。

**Comment by AriPSS** [comment]
@centrevillage 再度、お願いします！データはいつ削除してもらってもオッケーです！

**Comment by centrevillage** [comment]
@AriPSS 削除しましたのでご確認ください

**Comment by AriPSS** [comment]
@centrevillage 有難うございます。確認しました。

**Comment by AriPSS** [comment]
@centrevillage 再度、削除お願いします！タイミングは19:00以降でお願いします

**Comment by AriPSS** [comment]
@centrevillage 有難うございます。確認しました

**Comment by AriPSS** [comment]
@centrevillage 
ステージング環境にアップロードしてある電動舎（会社コード=DEN-001）の
*分類マスタ（categories）
*商品共通（product）
*自社在庫（stock_product）
を削除お願いします。
作業時間はいつでもO.K.です！

**Comment by AriPSS** [comment]
@centrevillage 登録件数が2件だけだそうなので、作業はなくなりました。closeします
