### ISSUE TITLE
API追加：category_id によるstock_productsの検索

### ISSUE THREAD

**Issue by miyabiit** [miyabiit/kenki-catalogdb#5]
(もしかすると、検索機能として用意されているのかもしれませんが)
以下のように、stock_productsを category_id で一致条件にて検索するAPIを追加してください。

```
myUrl = 'http://13.59.42.214/api/stock_products'
head = {'Authorization': 'Token myToken')}
param = {
  "limit": 1000,
  "category_id": 5 
}
response = requests.get(myUrl, headers=head, params=param)
```

**Comment by centrevillage** [comment]
@miyabiit 
下記のようにモデル名で検索条件を囲えば検索可能です:

```
myUrl = 'http://13.59.42.214/api/stock_products'
head = {'Authorization': 'Token myToken')}
param = {
  "limit": 1000,
  { "stock_product": {"category_id": 5} } 
}
response = requests.get(myUrl, headers=head, params=param)
```

**Comment by miyabiit** [comment]
@centrevillage やはり、実装あったのですね。了解です。本件、確認後、クローズします。

**Comment by miyabiit** [comment]
@centrevillage 試してみましたが、全件返ってきます。お手間ですが、curl かtest_api での例を示してもらえませんでしょうか？

**Comment by centrevillage** [comment]
@miyabiit おそらくRequest BodyがJSONデータとして解釈されていない気がします。
ヘッダーにcontent-typeの指定を追加してみてはいかがでしょうか:

```
head = {'Authorization': 'Token myToken', 'Content-Type': 'application/json'}
```

cURLの場合はこんな感じでいけました:

```
curl -X GET -D - -H "Content-Type: application/json" -H "Authorization: Token XXXXX" -d '{"limit": 1000, "stock_product": {"category_id": 42}}' http://13.59.42.214/api/stock_products
```

**Comment by miyabiit** [comment]
curlの例を見ながら、いろいろ試してみました。しかし、どうもいくつか矛盾があります。
テストのため、phthonで書いてみたのが、以下のプログラムです。
requestで生成されたurlは、うまくquery文字列を生成出来ていません。
curlの例からみると、期待されるのは、"GET メソッドで、かつ　request bodyに、パラメータを入れるケース"　だと思います。これは、矛盾していないでしょうか？
できれば、検索に関してはPOSTメソッドを利用する仕様に変更できないでしょうか？

試してみたプログラム

```
import requests
import json
import pprint

myToken = 'f/NRVPlG5rFGcIkfN/ZaSB0ftUshCRU9Bi3+NR+juWg='
myUrl = 'http://13.59.42.214/api/stock_products'
head = {'Authorization': 'Token {}'.format(myToken), 'Content-Type': 'application/json'}
param = {
    'limit': 15,
    'stock_product': {'category_id': 42}
}
try:
    response = requests.get(myUrl, headers=head, params=param)
except ResponseError:
    print('error')

print(response.url)
if response.status_code == 200:
    print(len(response.json()))
else:
    print(response.status_code)
```

結果

```
http://13.59.42.214/api/stock_products?limit=15&stock_product=category_id
# クエリー文字列がおかしい
15
# 検索条件は反映されず、出力件数制限のみ
```

**Comment by centrevillage** [comment]
@miyabiit 
おそらく、paramの渡し方を下記のようにすればいけそうに思います

```
param = {
    'limit': 15,
    'stock_product[category_id]':  42
}
```

ただ、見た目あまりスマートではないですね。
のちほど POST でも受けられるよう修正しようと思います。

**Comment by miyabiit** [comment]
@centrevillage 出来ました。ありがとうございます。そうか、そのクエリーの渡し方ありましたね。

**Comment by centrevillage** [comment]
@miyabiit よくよく考えると POST メソッドにするとCREATE操作とAPIが被ってしまいますね・・・
検索用APIを
`POST /api/stock_products/search`
という別のエンドポイントにしても良いでしょうか？

**Comment by centrevillage** [comment]
あるいは、 jQuery だと `$.param` メソッドでハッシュから `[]` ネスト形式のパラメーターに変換できるので、そちらであればプログラム上は同等に扱えるので、そちらが良いかもしれません。

https://api.jquery.com/jQuery.param/

**Comment by miyabiit** [comment]
jQueryは、使わない方向なので、エンドポイントの新設が良いと思います。結果、内容は、"テキスト検索”のissueに統合されることになりますね。このissueは、一旦 closeします。
