### ISSUE TITLE
本番環境のサイニチのデータ削除依頼

### ISSUE THREAD

**Issue by AriPSS** [miyabiit/kenki-catalogdb#50]
先日、本番環境にサイニチ（会社コード=SNI-001）という会社のデータをアップロードしました。
何回かステージング環境でお願いしている
*分類マスタ（categories）
*商品共通（product）
*自社在庫（stock_product）
を削除して下さい。（サイニチ分のみ）

削除は今日（2/19）の22:00以降で明日中までにお願い出来ればと思います。

**Comment by centrevillage** [comment]
@AriPSS 削除完了しました。ご確認お願いします。

**Comment by AriPSS** [comment]
@centrevillage 確認しました。問題ありません
