### ISSUE TITLE
アップロードツールの標準化

### ISSUE THREAD

**Issue by AriPSS** [miyabiit/kenki-catalogdb#7]
@centrevillage 現在登録されているcategories,products,stock_productsを削除して、添付ファイルを取り込んで下さい。

併せて、今回、CSVファイルの項目のうち、「product_tag」をユニークキーとして付番しましたので、これをproduct_codeとしてユニークキーとして下さい。また、現在、product_codeにセットされているデータは新しくproduct_nameで良いのでカラムを追加してそちらに移して下さい。
productsのCSVファイルのレイアウトを変える必要があれば、変更しますので言って下さい。

[掘削機.zip](https://github.com/miyabiit/kenki-catalogdb/files/4297672/default.zip)

**Comment by centrevillage** [comment]
@AriPSS 標準化を考えるのであれば、下記を修正していただくのが良いかと。

- categories
  - category_tag/parent_tag を廃止、代わりに parent_category_name を追加
    - 登録用一時IDから会社ごとのカテゴリ名の一意性によってリレーションを定義する方式に変える
- products
  - product_code を product_name にリネーム、product_tag を product_code にリネーム
     - 新しいテーブル項目名に合わせる
- stock_products
  - category_tag を category_name に変える（リネームだけでなく、内容もIDから名前に変える）
  - producct_tag を product_code にリネーム

登録用一時IDのようなものがあると、関連先のレコードを常に一括登録し直さなければならなくなるので、例えば今後categoriesは既存のもの参照してstock_productsを一括登録する場合などに困ります。

なので、基本的にテーブルのレコードが持っている一意キーを使って関連を定義した方が良いと思います。

**Comment by miyabiit** [comment]
@centrevillage 標準化のための修正ポイントは理解しました。以下、コメントと質問です。

### categories

parent_category_name にセットするのは、親のcategory_name ですよね。ユーザは、日本語で入れてくるので、微妙な差異が生じる可能性を危惧します。例えば、半角と全角、ユニコードでの判定での失敗とか。category_code (英数字）とかの導入が良いですかねえ？

### products

これは、了解です。

### stock_products

categoriesでの上記の意見を前提とすると、category_name ではなく、category_code とか。

ご意見求む！

**Comment by centrevillage** [comment]
@miyabiit 
> category_code (英数字）とかの導入が良いですかねえ？

結局同じ意味のカテゴリが複数登録されると運用上困ると思うので、そういうのは起きないようにしてもらうしかないと思います。
項目を増やすにしても、管理項目が増えてしまうので使い勝手が悪くなるかなと。

単純な半角・全角の表記揺れであれば、カテゴリ名の保存時にユニコード正規化 (https://ja.wikipedia.org/wiki/Unicode%E6%AD%A3%E8%A6%8F%E5%8C%96) をかけてしまう手もありますが、これではいかがでしょうか。

一応、rubyには標準でユニコード正規化のメソッドがあるので、対応は難しくないです。
https://docs.ruby-lang.org/ja/latest/method/String/i/unicode_normalize.html

**Comment by miyabiit** [comment]
@centrevillage  @AriPSS  了解です。parent_category_name の採用としましょう。
ツール標準化の作業としては、
* csv作成用のExcelシートテンプレの項目名の最終化　（飯田さん）
* upload プログラムの更新（中村さん）
* dbカラムの追加、更新（中村さん）
が主な作業かと思います。この認識であっているようであれば、各人にissueを発行し、このissueをクローズしようかと思います。

**Comment by centrevillage** [comment]
@AriPSS @miyabiit 

> dbカラムの追加、更新（中村さん）

すみません、　`parent_category_name` はCSV上だけの項目追加のつもりでした。
インポート後は `category_id` としてリレーションを持つことになるので、DBテーブルに `parent_category_name` は持たなくても良い想定です。

あと分類名のユニコード正規化は結局やりますか？

例えば `㈱` みたいな文字を `(株)` に統一できたりするので、表記ゆれ対策には結構有効だと思います。

**Comment by miyabiit** [comment]
@centrevillage parent_category_name は、はい！私もそのつもりでした。dbカラムの変更、追加は、stock_productsのユニークキー関連の話があったので、書いたまでです。（紛らわしくてすみません）。ユニコードの正規化は、見送りで良いです。他のissue（まだ、依頼していないものも含む）を優先しましょう。

**Comment by centrevillage** [comment]
了解しました。

**Comment by AriPSS** [comment]
@centrevillage @miyabiit 
CSVファイルを修正しました。内容の確認をお願いします。
#10 のproductsに追加するカラムもCSVファイルに追加してあります。

[マスタ_2020031901.zip](https://github.com/miyabiit/kenki-catalogdb/files/4352953/_2020031901.zip)

**Comment by centrevillage** [comment]
@AriPSS こちら (https://github.com/miyabiit/kenki-catalogdb/issues/10#issuecomment-602329365) にも書いたのですが、 product.csv の `model_name` を `producdt_model_name` に改名していただけるでしょうか？

**Comment by centrevillage** [comment]
@AriPSS stock_products.csv の video_url にURLでない文字列 (product_code + '-01')が入っているのが気になります。今は特にURLパターンチェックとかやっていないのですが、後々やりたくなった時に困らないかなと少し思いました。

**Comment by centrevillage** [comment]
@AriPSS @miyabiit 少し思ったのですが、いっそのことWebの画面からCSVアップロードできるようにしてはいかがでしょうか？

今回のカラム整理で各CSV間の一時IDが廃止されるので、個別にCSVアップロード処理が可能になりますので、無理なく実装できると思います。

ユーザーに見せたくないのであれば、直接URLを入力しないと見られない隠しページにする手もあります。

ご検討お願いします。

**Comment by AriPSS** [comment]
@centrevillage 
>@AriPSS こちら (#10 (comment)) にも書いたのですが、 product.csv の model_name を producdt_model_name に改名していただけるでしょうか？

修正したファイルを作成し直しました。
これでアップロードをお願い出来ればと。

[マスタ_2020032301.zip](https://github.com/miyabiit/kenki-catalogdb/files/4367226/_2020032301.zip)

**Comment by AriPSS** [comment]
@centrevillage CSVのアップロードはちょっとお待ち下さい。

**Comment by miyabiit** [comment]
@centrevillage @AriPSS web画面によるcsvアップロード機能を、このissue の最終ターゲットとしましょう。ただし、優先順位は、他のissueを優先してください。

@AriPSS video_url の内容は、空にしてください。当初の便宜上　product_codeを入れるフィールドが無かったための緊急措置でしたので。

@centrevillage 現在のstock_product.video_url は、全て空にしてくれませんか。

**Comment by centrevillage** [comment]
@miyabiit @AriPSS video_urlを空にしました。

**Comment by centrevillage** [comment]
@AriPSS Webの画面からのCSVアップロードに対応しました。

https://test.kenki-db.com/products

各一覧画面の右上にインポートボタンがあり、こちらを押すことでインポート画面に遷移します。

<img width="967" alt="スクリーンショット 2020-04-07 23 45 12" src="https://user-images.githubusercontent.com/1106404/78683126-defd8c80-7929-11ea-9aa8-582d0c785a47.png">


<img width="493" alt="スクリーンショット 2020-04-07 23 45 20" src="https://user-images.githubusercontent.com/1106404/78683136-e329aa00-7929-11ea-8eaa-926901e48b87.png">

分類と商品については一意キー(company_id+name, product_code)を使って、一括更新にも対応しています。
(自社在庫は登録のみです）

ご確認お願いします。

**Comment by miyabiit** [comment]
@centrevillage ありがとうございます。現在、staging/test環境がユーザレビューの対象となっているため、ちょっとこちらで試すのが怖い感じ。もう少しすると、ユーザからの情報提供があるようなので、それを持ってお試ししてみましょう。一旦、クローズします。
