### ISSUE TITLE
sub_categories 等の多対多のテーブルの検索

### ISSUE THREAD

**Issue by miyabiit** [miyabiit/kenki-catalogdb#9]
@centrevillage 例）sub_category.name に "新入荷"が含まれるstock_productsを検索したい。
/stock_products/search
{ limit: 1000, stock_product: {categories : {name: 新入荷" }}}
または、
{ limit: 1000, stock_product: {category : {  name: 新入荷" }}}
で検索してみましたが、失敗しました。おそらく、多対多で繋がっているテーブル同士であるためかと思います。

**Comment by centrevillage** [comment]
@miyabiit 
上の例だと `sub_category` の検索したいのに `category` の方を検索しようとしているクエリに見えるのですが、どちらの検索が行いたいのでしょうか。

`sub_category.name` の検索ならこちらのパラメータになるかと思います:

```
{ limit: 1000, stock_product: {sub_categories : { name: 新入荷" }}}
```

ちなみに、多対多の関連についても `has_many through` なよくあるケースは対応しています。

**Comment by miyabiit** [comment]
@centrevillage すみません。記載ミスです。実際には、以下のパラメータで検索しました。
検索結果 200 、[] (空）だったので、失敗したのかと思ったのですが、どうも　今回のアップロードでは、sub_categoriesが、登録されていない（つまり、検索結果は正常）だったようです。
sub_categoriesの登録が出来ていないのは問題ですが、検索そのものは正常でしたので、このissueは、クローズします。ありがとうございます。

```
param = {
  "limit": 1000,      
  "stock_product": {
          "sub_categories": {
              "name": "新入荷"
          }
  }
}
```
